### ISSUE TITLE
加到项目中直接报错

### ISSUE THREAD

**Issue by yilongchun** [codeWorm2015/channelEdit#1]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LRLChannelEditController", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_LRLChannelUnitModel", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RayLiu2015** [comment]
你是使用pod导入的吗, 如果使用pod导入的话, 在使用时导入头文件应该这样导入:
#import <LRLChannelEditController/LRLChannelEditController.h>
确认一下是不是我上述说的情况

**Comment by yilongchun** [comment]
我是直接拖进去的
#import "LRLChannelEditController.h" 这样引入的
编译的时候报错
我是新建的项目 什么都没有 直接引用的

**Comment by RayLiu2015** [comment]
<img width="882" alt="2017-07-05 11 17 59" src="https://user-images.githubusercontent.com/13360993/27847949-f09f3db0-6173-11e7-891d-c6b02a1e836d.png">
确认下 Build Phases->Compile Source 中, 相关.m文件是添加的

**Comment by yilongchun** [comment]
没有自动添加 我是手动加进去的

**Comment by RayLiu2015** [comment]
现在可以编译成功了?

**Comment by yilongchun** [comment]
现在可以了 2个resource 都要手动加 手动加进来就编译成功了

**Comment by RayLiu2015** [comment]
ok, 正常情况下直接拖拽到工程里, xcode会自动添加, 我这边也是直接自动添加的, 可能是你的xcode问题吧
