### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by yilongchun** [codeWorm2015/channelEdit#2]
默认前面两个固定 要修改为前3个固定 在哪里修改啊

**Comment by codeWorm2015** [comment]
当前还没有对完提供这样的接口, 如果你想更改, 可以修改 LRLChannelEditController.m  文件 第100行代码

**Comment by RayLiu2015** [comment]
当前还没有对外提供这样的接口, 如果你想更改, 可以修改 LRLChannelEditController.m 文件 第100行代码

**Comment by yilongchun** [comment]
这里我修改了 ，前三个是无法拖动，但是 其他的还是可以插入到第三个位置，把第三个往后挤，

**Comment by yilongchun** [comment]
这里我修改了 但是 其他的还是可以插入到第三个位置，把第三个往后挤

**Comment by RayLiu2015** [comment]
你下载最新代码, 我添加了一个属性, 用来修改固定按钮数的: 
@property (assign, nonatomic) NSUInteger fixedCount;
